### ISSUE TITLE
Promote the list in other awesome-lists

### ISSUE THREAD

**Issue by mnasyrov** [gabrielizalo/Awesome-JavaScript-Crypto-Libraries#1]
Hi! It would be great to promote this gem in more high level lists like [Awesome](https://github.com/sindresorhus/awesome) or [Awesome JavaScript](https://github.com/sorrycc/awesome-javascript).

**Comment by gabrielizalo** [comment]
Thanks... I'll working on it  (y)

**Comment by gabrielizalo** [comment]
Done: https://github.com/sorrycc/awesome-javascript/pull/588
Thanks
